name: "Acer Predator Triton 500 P515-51"
reaction: 10
pollTickMs: 1000
cmdPort: 0x66 #! required
dataPort: 0x62 #! required
zones: 
  - name: System
    address: 0xA9
    min: 0x00
    max: 0xff
  - name: CPU Zone
    address: 0xA8 # required!
    min: 0x00 # default 0x00
    max: 0xff # default 0xff
    fans:
      - name: Fan 1
        address: 0x93 # required!
        auto: 0x04 # default 0x04
        manual: 0x14 # default 0x14
        wrReg: 0x94 # required!
        rdReg: 0x95 # required!
        min: 0xff # default 0xff
        max: 0x00 # default 0x00
  - name: GPU Zone
    address: 0xB8
    min: 0x00
    max: 0xff
    fans:
      - name: Fan 1
        address: 0x96 # required!
        auto: 0x04
        manual: 0x14
        wrReg: 0x97
        rdReg: 0x98
        min:    0xff
        max:    0x1D
      - name: Fan 2
        address: 0x9A
        auto: 0x04
        manual: 0x14
        wrReg: 0x9B
        rdReg: 0x9C
        min:    0xff
        max:    0x00
    levels:
      - enterTemp: 30.0
        freq: 50.0
      - enterTemp: 40.0
        freq: 55.0
      - enterTemp: 45.0
        freq: 60.0
      - enterTemp: 50.0
        freq: 65.0
      - enterTemp: 55.0
        freq: 70.0
      - enterTemp: 60.0
        freq: 75.0
      - enterTemp: 65.0
        freq: 80.0
      - enterTemp: 70.0
        freq: 85.0
      - enterTemp: 75.0
        freq: 90.0
      - enterTemp: 80.0
        freq: 100.0
config: 
  maxTemp: 0x64 # default 0x5a (100 C)