name: release
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build static binaries
      uses: skynet-core/nim@v1.2
    - name: Archive nsense binary
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: |
          ${{ github.workspace }}/nsense
          ${{ github.workspace }}/nsensepkg/cli/nsensectl
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download nsense artifact
      uses: actions/download-artifact@v2
      with:
        name: binaries
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
    - name: Generate nfpm config
      id: nfpm-cfg
      shell: bash
      run: |
        git fetch --prune --tags
        version=$(git tag --list --sort=taggerdate | tail -n 1 | tr -d 'v' | sed 's|-beta||')
        cat ./nfpm.template.yaml | sed -e "s|@version|$version|g" > ./nfpm.yaml
        echo "::set-output name=version::$version"
    - name: Create deb package
      id: deb-pack
      uses: skynet-core/nfpm@v1.5
      with:
        config: nfpm.yaml
        packager: deb
    - name: Create rpm package
      id: rpm-pack
      uses: skynet-core/nfpm@v1.5
      with:
        config: nfpm.yaml
        packager: rpm
    - name: Archive nsense packages
      uses: actions/upload-artifact@v2
      with:
        name: packages
        path: |
          ${{ github.workspace }}/*.deb
          ${{ github.workspace }}/*.rpm
    - name: Install Github-Release
      shell: bash
      run: go get github.com/github-release/github-release
    - name: Draft new release
      env:
        LABEL: 'release'
        VERSION: ${{ steps.nfpm-cfg.outputs.version }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        github-release -v release -u skynet-core -r nord-sense -t v$VERSION -n $LABEL
        github-release -v upload -u skynet-core -r nord-sense -t v$VERSION -f *.deb -n ${{ steps.deb-pack.outputs.package }}
        github-release -v upload -u skynet-core -r nord-sense -t v$VERSION -f *.rpm -n ${{ steps.rpm-pack.outputs.package }}
    - name: Deploy signed to repository
      env: 
        SSH_PRIV_KEY: ${{ secrets.SSH_PRIV_KEY }}
      run: |
        echo $SSH_PRIV_KEY | sftp -i /dev/stdin github@wehack.network <<EOF
        cd deb/amd64
        mkdir lock
        put ${{ steps.deb-pack.outputs.package }}
        rmdir lock
        exit
        EOF