name: release-trigger
on:
  pull_request:
    branches:
      - develop
    types: [closed]
jobs:
  commit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: 'Check out code'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: 'Increment version'
      env:
        HEAD_REF: ${{ github.event.pull_request.head.ref }}
      shell: sh
      id: meta-run
      run: |
        git fetch --prune --tags
        version=$(git tag --list --sort=taggerdate | tail -n 1 | tr -d 'v' | sed 's|-beta||')
        fix=$(echo $version | cut -d '.' -f3)
        minor=$(echo $version | cut -d '.' -f2)
        major=$(echo $version | cut -d '.' -f1)
        case $HEAD_REF in
          fix/* )
            fix=$(( $fix + 1 ))
          ;;
          feature/* )
            minor=$(( $minor + 1 ))
            fix=0
          ;;
          next/*  )
            major=$(( $major + 1 ))
            minor=0
            fix=0
          ;;
          * ) 
            exit 1
          ;;
        esac
        new_ver="$major.$minor.$fix"
        cat nsense.nimble | awk "/version/{sub(/[0-9]+.[0-9]+.[0-9]+/,\"$new_ver\",\$0)};1" > temp.nimble && mv temp.nimble nsense.nimble
        echo "::set-output name=version::v$new_ver"        
    - name: Commit changes file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: 'release: develop'
        branch: develop
        commit_user_name: skynet-core
        tagging_message: ${{ steps.meta-run.outputs.version }}-beta
    - name: Trigger repository custom event
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        event-type: 'pre-release'
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'